// Generated by gencpp from file h_robix_control/GetGroupMotorDataRequest.msg
// DO NOT EDIT!


#ifndef H_ROBIX_CONTROL_MESSAGE_GETGROUPMOTORDATAREQUEST_H
#define H_ROBIX_CONTROL_MESSAGE_GETGROUPMOTORDATAREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace h_robix_control
{
template <class ContainerAllocator>
struct GetGroupMotorDataRequest_
{
  typedef GetGroupMotorDataRequest_<ContainerAllocator> Type;

  GetGroupMotorDataRequest_()
    : motor1_id(0)
    , motor2_id(0)
    , motor3_id(0)
    , motor4_id(0)
    , motor5_id(0)
    , motor6_id(0)
    , data_required()  {
    }
  GetGroupMotorDataRequest_(const ContainerAllocator& _alloc)
    : motor1_id(0)
    , motor2_id(0)
    , motor3_id(0)
    , motor4_id(0)
    , motor5_id(0)
    , motor6_id(0)
    , data_required(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _motor1_id_type;
  _motor1_id_type motor1_id;

   typedef uint8_t _motor2_id_type;
  _motor2_id_type motor2_id;

   typedef uint8_t _motor3_id_type;
  _motor3_id_type motor3_id;

   typedef uint8_t _motor4_id_type;
  _motor4_id_type motor4_id;

   typedef uint8_t _motor5_id_type;
  _motor5_id_type motor5_id;

   typedef uint8_t _motor6_id_type;
  _motor6_id_type motor6_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_required_type;
  _data_required_type data_required;





  typedef boost::shared_ptr< ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetGroupMotorDataRequest_

typedef ::h_robix_control::GetGroupMotorDataRequest_<std::allocator<void> > GetGroupMotorDataRequest;

typedef boost::shared_ptr< ::h_robix_control::GetGroupMotorDataRequest > GetGroupMotorDataRequestPtr;
typedef boost::shared_ptr< ::h_robix_control::GetGroupMotorDataRequest const> GetGroupMotorDataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator1> & lhs, const ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator2> & rhs)
{
  return lhs.motor1_id == rhs.motor1_id &&
    lhs.motor2_id == rhs.motor2_id &&
    lhs.motor3_id == rhs.motor3_id &&
    lhs.motor4_id == rhs.motor4_id &&
    lhs.motor5_id == rhs.motor5_id &&
    lhs.motor6_id == rhs.motor6_id &&
    lhs.data_required == rhs.data_required;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator1> & lhs, const ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace h_robix_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d795fe8db7df6ecaaf527340a3fe3a91";
  }

  static const char* value(const ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd795fe8db7df6ecaULL;
  static const uint64_t static_value2 = 0xaf527340a3fe3a91ULL;
};

template<class ContainerAllocator>
struct DataType< ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "h_robix_control/GetGroupMotorDataRequest";
  }

  static const char* value(const ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 motor1_id\n"
"uint8 motor2_id\n"
"uint8 motor3_id\n"
"uint8 motor4_id\n"
"uint8 motor5_id\n"
"uint8 motor6_id\n"
"string data_required\n"
;
  }

  static const char* value(const ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor1_id);
      stream.next(m.motor2_id);
      stream.next(m.motor3_id);
      stream.next(m.motor4_id);
      stream.next(m.motor5_id);
      stream.next(m.motor6_id);
      stream.next(m.data_required);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetGroupMotorDataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::h_robix_control::GetGroupMotorDataRequest_<ContainerAllocator>& v)
  {
    s << indent << "motor1_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motor1_id);
    s << indent << "motor2_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motor2_id);
    s << indent << "motor3_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motor3_id);
    s << indent << "motor4_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motor4_id);
    s << indent << "motor5_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motor5_id);
    s << indent << "motor6_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motor6_id);
    s << indent << "data_required: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data_required);
  }
};

} // namespace message_operations
} // namespace ros

#endif // H_ROBIX_CONTROL_MESSAGE_GETGROUPMOTORDATAREQUEST_H
