// Generated by gencpp from file h_robix_control/GetGroupMotorData.msg
// DO NOT EDIT!


#ifndef H_ROBIX_CONTROL_MESSAGE_GETGROUPMOTORDATA_H
#define H_ROBIX_CONTROL_MESSAGE_GETGROUPMOTORDATA_H

#include <ros/service_traits.h>


#include <h_robix_control/GetGroupMotorDataRequest.h>
#include <h_robix_control/GetGroupMotorDataResponse.h>


namespace h_robix_control
{

struct GetGroupMotorData
{

typedef GetGroupMotorDataRequest Request;
typedef GetGroupMotorDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGroupMotorData
} // namespace h_robix_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::h_robix_control::GetGroupMotorData > {
  static const char* value()
  {
    return "1d809d6a5bd5cdb4eacfae0651cc8f04";
  }

  static const char* value(const ::h_robix_control::GetGroupMotorData&) { return value(); }
};

template<>
struct DataType< ::h_robix_control::GetGroupMotorData > {
  static const char* value()
  {
    return "h_robix_control/GetGroupMotorData";
  }

  static const char* value(const ::h_robix_control::GetGroupMotorData&) { return value(); }
};


// service_traits::MD5Sum< ::h_robix_control::GetGroupMotorDataRequest> should match
// service_traits::MD5Sum< ::h_robix_control::GetGroupMotorData >
template<>
struct MD5Sum< ::h_robix_control::GetGroupMotorDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::h_robix_control::GetGroupMotorData >::value();
  }
  static const char* value(const ::h_robix_control::GetGroupMotorDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::h_robix_control::GetGroupMotorDataRequest> should match
// service_traits::DataType< ::h_robix_control::GetGroupMotorData >
template<>
struct DataType< ::h_robix_control::GetGroupMotorDataRequest>
{
  static const char* value()
  {
    return DataType< ::h_robix_control::GetGroupMotorData >::value();
  }
  static const char* value(const ::h_robix_control::GetGroupMotorDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::h_robix_control::GetGroupMotorDataResponse> should match
// service_traits::MD5Sum< ::h_robix_control::GetGroupMotorData >
template<>
struct MD5Sum< ::h_robix_control::GetGroupMotorDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::h_robix_control::GetGroupMotorData >::value();
  }
  static const char* value(const ::h_robix_control::GetGroupMotorDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::h_robix_control::GetGroupMotorDataResponse> should match
// service_traits::DataType< ::h_robix_control::GetGroupMotorData >
template<>
struct DataType< ::h_robix_control::GetGroupMotorDataResponse>
{
  static const char* value()
  {
    return DataType< ::h_robix_control::GetGroupMotorData >::value();
  }
  static const char* value(const ::h_robix_control::GetGroupMotorDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // H_ROBIX_CONTROL_MESSAGE_GETGROUPMOTORDATA_H
