hexa_haibot:
# Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

# Position Controllers ---------------------------------------

    coxa_1_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: coxa_1_joint
        pid: {p: 100.0, i: 0.0, d: 0.0}

    coxa_2_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: coxa_2_joint
        pid: {p: 100.0, i: 0.0, d: 0.0}

    coxa_3_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: coxa_3_joint
        pid: {p: 100.0, i: 0.0, d: 0.0}

    coxa_4_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: coxa_4_joint
        pid: {p: 100.0, i: 0.0, d: 0.0}

    coxa_5_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: coxa_5_joint
        pid: {p: 100.0, i: 0.0, d: 0.0}

    coxa_6_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: coxa_6_joint
        pid: {p: 100.0, i: 0.0, d: 0.0}

    femur_1_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: femur_1_joint
        pid: {p: 100.0, i: 0.0, d: 0.0}

    femur_2_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: femur_2_joint
        pid: {p: 100.0, i: 0.0, d: 0.0}

    femur_3_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: femur_3_joint
        pid: {p: 100.0, i: 0.0, d: 0.0}

    femur_4_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: femur_4_joint
        pid: {p: 100.0, i: 0.0, d: 0.0}

    femur_5_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: femur_5_joint
        pid: {p: 100.0, i: 0.0, d: 0.0}

    femur_6_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: femur_6_joint
        pid: {p: 100.0, i: 0.0, d: 0.0}

    tibia_1_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: tibia_1_joint
        pid: {p: 100.0, i: 0.0, d: 0.0}

    tibia_2_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: tibia_2_joint
        pid: {p: 100.0, i: 0.0, d: 0.0}

    tibia_3_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: tibia_3_joint
        pid: {p: 100.0, i: 0.0, d: 0.0}

    tibia_4_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: tibia_4_joint
        pid: {p: 100.0, i: 0.0, d: 0.0}

    tibia_5_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: tibia_5_joint
        pid: {p: 100.0, i: 0.0, d: 0.0}

    tibia_6_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: tibia_6_joint
        pid: {p: 100.0, i: 0.0, d: 0.0}


controller_joint_names: [ 'coxa_1_joint', 
                          'femur_1_joint', 
                          'tibia_1_joint', 
                          'coxa_3_joint', 
                          'femur_3_joint', 
                          'tibia_3_joint', 
                          'coxa_5_joint', 
                          'femur_5_joint', 
                          'tibia_5_joint', 
                          'coxa_2_joint', 
                          'femur_2_joint', 
                          'tibia_2_joint', 
                          'coxa_4_joint', 
                          'femur_4_joint', 
                          'tibia_4_joint', 
                          'coxa_6_joint', 
                          'femur_6_joint', 
                          'tibia_6_joint' ]
