# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from h_robix_control/ButtonData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ButtonData(genpy.Message):
  _md5sum = "374b4b2e2aa0d2e31b123b1290f7a442"
  _type = "h_robix_control/ButtonData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool right_front_leg
bool right_middle_leg
bool right_back_leg
bool left_front_leg
bool left_middle_leg
bool left_back_leg"""
  __slots__ = ['right_front_leg','right_middle_leg','right_back_leg','left_front_leg','left_middle_leg','left_back_leg']
  _slot_types = ['bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       right_front_leg,right_middle_leg,right_back_leg,left_front_leg,left_middle_leg,left_back_leg

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ButtonData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.right_front_leg is None:
        self.right_front_leg = False
      if self.right_middle_leg is None:
        self.right_middle_leg = False
      if self.right_back_leg is None:
        self.right_back_leg = False
      if self.left_front_leg is None:
        self.left_front_leg = False
      if self.left_middle_leg is None:
        self.left_middle_leg = False
      if self.left_back_leg is None:
        self.left_back_leg = False
    else:
      self.right_front_leg = False
      self.right_middle_leg = False
      self.right_back_leg = False
      self.left_front_leg = False
      self.left_middle_leg = False
      self.left_back_leg = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6B().pack(_x.right_front_leg, _x.right_middle_leg, _x.right_back_leg, _x.left_front_leg, _x.left_middle_leg, _x.left_back_leg))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.right_front_leg, _x.right_middle_leg, _x.right_back_leg, _x.left_front_leg, _x.left_middle_leg, _x.left_back_leg,) = _get_struct_6B().unpack(str[start:end])
      self.right_front_leg = bool(self.right_front_leg)
      self.right_middle_leg = bool(self.right_middle_leg)
      self.right_back_leg = bool(self.right_back_leg)
      self.left_front_leg = bool(self.left_front_leg)
      self.left_middle_leg = bool(self.left_middle_leg)
      self.left_back_leg = bool(self.left_back_leg)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6B().pack(_x.right_front_leg, _x.right_middle_leg, _x.right_back_leg, _x.left_front_leg, _x.left_middle_leg, _x.left_back_leg))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.right_front_leg, _x.right_middle_leg, _x.right_back_leg, _x.left_front_leg, _x.left_middle_leg, _x.left_back_leg,) = _get_struct_6B().unpack(str[start:end])
      self.right_front_leg = bool(self.right_front_leg)
      self.right_middle_leg = bool(self.right_middle_leg)
      self.right_back_leg = bool(self.right_back_leg)
      self.left_front_leg = bool(self.left_front_leg)
      self.left_middle_leg = bool(self.left_middle_leg)
      self.left_back_leg = bool(self.left_back_leg)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6B = None
def _get_struct_6B():
    global _struct_6B
    if _struct_6B is None:
        _struct_6B = struct.Struct("<6B")
    return _struct_6B
