(cl:defpackage h_robix_control-srv
  (:use )
  (:export
   "GETGROUPMOTORDATA"
   "<GETGROUPMOTORDATA-REQUEST>"
   "GETGROUPMOTORDATA-REQUEST"
   "<GETGROUPMOTORDATA-RESPONSE>"
   "GETGROUPMOTORDATA-RESPONSE"
   "GETPOSITION"
   "<GETPOSITION-REQUEST>"
   "GETPOSITION-REQUEST"
   "<GETPOSITION-RESPONSE>"
   "GETPOSITION-RESPONSE"
  ))

